## Taller Computacion Cientifica  - German Daniel Rojas 

#### 1. Import the numpy package under the name `np` 

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration ( )

In [2]:
print(np.__version__)
np.show_config()

1.18.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10

In [3]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array

In [4]:
arr = np.array([None for x in range(5)])
print("{} bytes".format((arr.size * arr.itemsize)))

40 bytes


#### 5. How to get the documentation of the numpy add function from the command line? 

In [12]:
print(np.info(np.arange))

arange([start,] stop[, step,], dtype=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.

Parameters
----------
start : number, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : number
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : number, optional
    Spacing between values.  For any output `out`, this is the distance
    between two adjacent values, ``out[i+1] - out[i]``

#### 6. Create a null vector of size 10 but the fifth value which is 1

In [13]:
arr  = np.zeros(10)
arr[4] = 1;

#### 7. Create a vector with values ranging from 10 to 49 

In [6]:
arr_d = np.arange(10,50)
print(arr_d)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last)

In [10]:
arr_x = np.arange(10)
print(arr_x)
print("Reverse : ",arr_x[::-1])

[0 1 2 3 4 5 6 7 8 9]
Reverse :  [9 8 7 6 5 4 3 2 1 0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 

In [15]:
arr = np.random.random_sample((3, 3))*8
print(arr)


[[6.10881405 3.6345531  0.6404783 ]
 [1.15187311 1.59393152 4.87018397]
 [5.47526797 4.29624872 5.50064184]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0]


In [18]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix

In [19]:
arrT = np.eye(3)
print(arrT)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [20]:
arr = np.random.random((3,3,3))
print(arr)

[[[0.46520726 0.49155026 0.4497204 ]
  [0.0189892  0.70786628 0.89443673]
  [0.0462813  0.41773309 0.48280555]]

 [[0.53646197 0.14817293 0.34983924]
  [0.76566105 0.41742082 0.37671155]
  [0.25356643 0.20002751 0.16852188]]

 [[0.38197524 0.81870408 0.5879103 ]
  [0.79594695 0.62329771 0.64005654]
  [0.16665655 0.57442788 0.04903843]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values 

In [21]:
Pot = np.random.random((10,10))
Potmin, Potmax = Pot.min(), Pot.max()
print(Potmin, Potmax)

0.0034511129451806344 0.964587049450534


#### 14. Create a random vector of size 30 and find the mean value

In [23]:
arr = np.arange(30)
print(np.mean(arr))

14.5


#### 15. Create a 2d array with 1 on the border and 0 inside

In [66]:
arr_l = np.ones((6,6))
arr_l[1:-1,1:-1] = 0
print(arr_l)


[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [70]:

Arr_o = np.ones((5,5))
Arr_o = np.pad(Arr_o, pad_width=1, mode='constant', constant_values=0)
print(Arr_o)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? 
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [79]:
print(np.nan*0) ## nan
print(np.nan == np.nan) ## False
print(np.inf > np.nan) ## False
print(np.nan -np.nan) ## nan
print(np.nan in set([np.nan])) ## True
print(0.3 == 3*0.1) ## False


nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [81]:
arr_d = np.diag(np.arange(1,5))
print(arr_d)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [42]:
arr_j = np.zeros((8,8))
arr_j[1::2,::2] = 1
arr_j[::2,1::2] = 1
print(arr_j)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [35]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function

In [36]:
Arr_p = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Arr_p)



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix

In [37]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-1.59418053 -1.77538077 -1.97399419  0.98273027  0.51027043]
 [ 0.08656711 -0.21658251  1.25815685  0.84365187  0.39684168]
 [-1.57930017  0.9101595   0.62906703 -1.3155242  -0.63143424]
 [ 0.31289857 -0.16382159  1.40357501  0.55118696 -0.40512972]
 [ 0.26469085 -0.30837411  0.06473139  1.75995707 -0.01076255]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [38]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

/home/droro/Documents/CientificaScripts/env/lib/python3.6/site-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [39]:
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [44]:

x = np.arange(11)
x[(3 < x) & (x <= 8)] *= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script?
```python
# Author: Jake VanderPlas
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [58]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal?
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [64]:
Z  = np.arange(10);
print(Z**Z) ##Legal
print(2 << Z >> 2) ## Legal
print(Z <- Z) ##Legal
print(1j*Z) ##Legal
print(Z/1/1)## Legal
print(Z<Z>Z) ##Ilegal

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [65]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/home/droro/Documents/CientificaScripts/env/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/home/droro/Documents/CientificaScripts/env/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ?

In [66]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ -4. -10.   3.  -5. -10.  10.  -1.  -5.  -6.  -4.]


#### 30. How to find common values between two arrays?

In [69]:
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([1,22,3,5,5,8,9])
print(np.intersect1d(arr1,arr2))

[1 3 5]


#### 31. How to ignore all numpy warnings (not recommended)?

In [70]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0


#### 32. Is the following expressions true?
```pythonnp.sqrt(-1) == np.emath.sqrt(-1)
```

In [2]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


/home/droro/Documents/CientificaScripts/env/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


#### 33. How to get the dates of yesterday, today and tomorrow?

In [5]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(yesterday)
print(today)
print(tomorrow)

2020-02-22
2020-02-23
2020-02-24


#### 34. How to get all the dates corresponding to the month of July 2016?

In [6]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [7]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods

In [8]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[9. 9. 5. 1. 7. 0. 7. 4. 9. 0.]
[9. 9. 5. 1. 7. 0. 7. 4. 9. 0.]
[9. 9. 5. 1. 7. 0. 7. 4. 9. 0.]
[9 9 5 1 7 0 7 4 9 0]
[9. 9. 5. 1. 7. 0. 7. 4. 9. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4

In [9]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array

In [10]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [11]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it

In [12]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.06356489 0.11110482 0.15720453 0.22281347 0.26074086 0.49953718
 0.6835109  0.73747808 0.760522   0.81825265]


#### 41. How to sum a small array faster than np.sum?

In [14]:

Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal

In [23]:
A = np.random.randint(0,8,6)
B = np.random.randint(0,2,6)
print(A)
print(B)
print(np.array_equal(A,B))

[1 2 1 0 3 5]
[0 0 1 1 0 1]
False


#### 43. Make an array immutable (read-only)

In [24]:
Z = np.ones(10)
Z.flags.writeable = False
Z[0] = 0

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar
coordinates

In [28]:
Z = np.random.random((10,2))
print(Z,'\n')
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = (np.arctan2(Y,X)*180)/np.pi
print(R) ## Modulo
print(T) ##Fase Grados

[[0.60018784 0.45102796]
 [0.25045754 0.71909728]
 [0.80624101 0.81214445]
 [0.96921269 0.34221796]
 [0.30532322 0.42873326]
 [0.48979085 0.14212972]
 [0.52211586 0.17480106]
 [0.96430583 0.59156438]
 [0.34521715 0.26028702]
 [0.37786535 0.65870274]] 

[0.75076738 0.76146561 1.14437895 1.02785523 0.52634065 0.50999601
 0.55060002 1.13129756 0.43234733 0.75938891]
[36.92405671 70.79706007 45.20899902 19.44754626 54.54335747 16.18191077
 18.51021709 31.52750786 37.01558292 60.15922783]


#### 45. Create random vector of size 10 and replace the maximum value by 0

In [34]:


Z = np.random.random(10)
print(Z,'\n')
Z[Z.argmax()] = 0
print(Z)

[0.52559899 0.39554157 0.6738881  0.37841321 0.17162833 0.80253198
 0.52693386 0.84758371 0.23742929 0.67771221] 

[0.52559899 0.39554157 0.6738881  0.37841321 0.17162833 0.80253198
 0.52693386 0.         0.23742929 0.67771221]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

In [36]:
Z = np.zeros((5,5), [('x',float),('y',float)])
print(Z,'\n')
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]] 

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [37]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type

In [42]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array?

In [41]:

Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector?

In [43]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

45


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b)

In [48]:


Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/home/droro/Documents/CientificaScripts/env/lib/python3.6/site-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point
distances

In [47]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)


[[0.         0.33752014 0.20024933 0.56969623 0.58069646 0.3526151
  0.4631316  0.42931718 0.35613313 0.14067895]
 [0.33752014 0.         0.28875711 0.74970528 0.60958875 0.5554935
  0.75747911 0.75398509 0.23757714 0.20482207]
 [0.20024933 0.28875711 0.         0.46771478 0.39810536 0.26684445
  0.65472536 0.60094041 0.1780728  0.13808   ]
 [0.56969623 0.74970528 0.46771478 0.         0.30229977 0.21742521
  0.84594483 0.7276717  0.55194669 0.59582804]
 [0.58069646 0.60958875 0.39810536 0.30229977 0.         0.32090362
  0.98170329 0.89001436 0.37371995 0.53268446]
 [0.3526151  0.5554935  0.26684445 0.21742521 0.32090362 0.
  0.67563079 0.57417085 0.39241527 0.38474326]
 [0.4631316  0.75747911 0.65472536 0.84594483 0.98170329 0.67563079
  0.         0.13706668 0.81918121 0.59489608]
 [0.42931718 0.75398509 0.60094041 0.7276717  0.89001436 0.57417085
  0.13706668 0.         0.77501558 0.56936925]
 [0.35613313 0.23757714 0.1780728  0.55194669 0.37371995 0.39241527
  0.81918121 0.7750155

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [49]:
# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[93 79  0 56 61 71 64 52 53 87]


#### 54. How to read the following file?
```1, 2, 3, 4, 5
6, , , 7, 8
, , 9,10,11
```

In [50]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays?

In [51]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
